services:
  - type: web
    name: eventdream
    env: php
    plan: free
    buildCommand: |
      cp /etc/secrets/.env .env
      composer install
      php artisan migrate --force
      php artisan config:cache
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:TqBKEQRIWGw/OhOUcVxg7x0Mhp6n4O5/KbYaYGIo5fs=
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /etc/secrets/database.sqlite
