services:
  - type: web
    name: eventdream
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: |
      composer install
      php artisan migrate --force
      php artisan config:cache
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:TqBKEQRIWGw/OhOUcVxg7x0Mhp6n4O5/KbYaYGIo5fs=
